Iteration #5 Bids initial flow
andreyQw/auction pull request #8
Opened 2018-08-23 13:32 UTC by andreyQw

Iteration #5 Bids initial flow

2018-08-28 08:12 UTC, an-tk requested changes
тесты посмотрю когда будет исправлен баг с моими/всеми лотами

2018-08-28 08:12 UTC, an-tk commented on app/controllers/lots_controller.rb
> +    filter = params[:filter]
тут что-то не так
у нас есть **все лоты** и **мои лоты**
**все лоты** это лоты. in_process
**мои лоты** это лоты которые я создал и лоты в которых принимаю участие

мои лоты фильтруются: 
- created - те что я создал
- participation - те которые бидил
- all  - те что создал и те что бидил

2018-08-28 08:12 UTC, an-tk commented on app/controllers/lots_controller.rb
> +      return render_resources lots
`return render_resources lots` вынести из if-else

2018-08-28 08:12 UTC, an-tk commented on app/controllers/lots_controller.rb
> +    LotsStatusInProcessJob.set(wait_until: lot.lot_start_time).perform_later(lot.id)
не думаю что эти джобы стоит делать в контроллере

2018-08-28 08:12 UTC, an-tk commented on app/controllers/lots_controller.rb
> +    LotsStatusClosedJob.set(wait_until: lot.lot_end_time).perform_later(lot.id)
что произойдет с джобами если мы отредактируем лот? мы же можем его редактировать до публикации?

2018-08-28 08:12 UTC, an-tk commented on app/models/lot.rb
> +  def lot_status_closed
??

2018-08-28 08:12 UTC, an-tk commented on app/models/lot.rb
> +  # after_create :lot_status_closed
??

2018-08-28 08:12 UTC, an-tk commented on app/models/bid.rb
> +    end
```errors.add(:lot, "Lot status must be in_process") unless lot.in_process?```
так намного проще читается

2018-08-28 08:12 UTC, an-tk commented on app/models/bid.rb
> +    end
```attribute should be set to :base if the error is not directly associated with a single attribute.```
так написано в доках к Active Model Errors
так что давай заменим на 
```errors.add(:base, "Lot status must be in_process")```

2018-08-28 08:12 UTC, an-tk commented on app/models/user.rb
> +  def self.all_except(user_id)
это можно сделать скоупом? и назвать попонятнее

2018-08-28 08:12 UTC, an-tk commented on app/serializers/bid_serializer.rb
> +  attributes :id, :proposed_price, :created_at, :user_id, :lot_id
тут нам все таки нужен зашифрованное имя пользователя

2018-08-28 08:12 UTC, an-tk commented on app/serializers/lot_serializer.rb
> +  # attributes :id, :user_id, :title, :image, :description, :status, :current_price, :estimated_price, :lot_start_time, :lot_end_time
? 
image  :description  :estimated_price и проее уже не нужны

2018-08-28 08:12 UTC, an-tk commented on db/migrate/20180820073221_add_alias_to_bids.rb
> -class AddAliasToBids < ActiveRecord::Migration[5.2]
что это?

2018-08-30 09:14 UTC, andreyQw commented on app/controllers/lots_controller.rb
> +    filter = params[:filter]
поправил работу фильтров

2018-08-30 09:15 UTC, andreyQw commented on app/controllers/lots_controller.rb
> +      return render_resources lots
изменил

2018-08-30 09:17 UTC, andreyQw commented on app/controllers/lots_controller.rb
> +    LotsStatusInProcessJob.set(wait_until: lot.lot_start_time).perform_later(lot.id)
вынес в колбек after_create

2018-08-30 09:18 UTC, andreyQw commented on app/controllers/lots_controller.rb
> +    LotsStatusClosedJob.set(wait_until: lot.lot_end_time).perform_later(lot.id)
добавил перезапись бжобов после обновления лота

2018-08-30 09:21 UTC, andreyQw commented on app/models/lot.rb
> +  def lot_status_closed
добавил логику закрытия лота и определения победителя

2018-08-30 09:26 UTC, andreyQw commented on app/models/bid.rb
> +    end
поправил

2018-08-30 09:26 UTC, andreyQw commented on app/models/user.rb
> +  def self.all_except(user_id)
сделал скоупом

2018-08-30 09:27 UTC, andreyQw commented on app/serializers/bid_serializer.rb
> +  attributes :id, :proposed_price, :created_at, :user_id, :lot_id
добавил шифрование для покупателя

2018-08-30 09:33 UTC, andreyQw commented on db/migrate/20180820073221_add_alias_to_bids.rb
> -class AddAliasToBids < ActiveRecord::Migration[5.2]
изначально думал хранить шифрованного юзера для бидов в базе, сейчас сделано с шифрованием юзера в сериалайзере

2018-09-03 07:46 UTC, merged